version: 2.1

parameters:
  trigger:
    type: boolean
    default: true

  demo:
    type: boolean
    default: false
  sample:
    type: boolean
    default: false

executors:
  node:
    docker:
      - image: circleci/node:10.15.3

jobs:
  trigger-workflows:
    executor: node
    steps:
      - checkout
      - run:
          name: Trigger workflows
          command: chmod +x .circleci/circle_trigger.sh && ls -l && .circleci/circle_trigger.sh

  package-install-and-lint:
    parameters:
      package_name:
        type: string
    executor: node
    steps:
      - checkout:
          path: ~/monorepo
      - run:
          name: Package install
          command: npm install
      - run:
          name: Lint
          command: npm run lint

  build:
    parameters:
      package_name:
        type: string
    executor: node
    steps:
      - checkout:
          path: ~/monorepo
      - run:
          name: Build
          command: echo "ビルド << parameters.package_name >> ..."

  echo:
    parameters:
      package_name:
        type: string
    executor: node
    steps:
      - checkout:
          path: ~/monorepo
      - run:
          command: echo "Hello World tg."

workflows:
  version: 2
  ci:
    when: << pipeline.parameters.trigger >>
    jobs:
      - trigger-workflows

  demo:
    when: << pipeline.parameters.demo >>
    jobs:
      - package-install-and-lint:
            name: demo-install
            package_name: demo      
      - build:
          name: demo-build
          package_name: demo
      - echo:
          name: demo-build
          package_name: demo
  sample:
    when: << pipeline.parameters.sample >>
    jobs:
      - package-install-and-lint:
          name: sample-install
          package_name: sample
      - build:
          name: sample-build
          package_name: sample
      - echo:
          name: sample-build
          package_name: sample
