version: 2.1

parameters:
  # 変更検知フラグ
  trigger:
    type: boolean
    default: true
  # 各プロジェクト分のフラグを用意する
  demo:
    type: boolean
    default: false
  sample:
    type: boolean
    default: false

# 実行環境
executors:
  node:
    docker:
      - image: circleci/node:10.15.3

# node_modulesのキャッシュ戦略
references:
  cache_key: &cache_key v1-dependencies-{{ checksum "<< pipeline.parameters.package_name >>/package-lock.json" }}
  save_node_modules: &save_node_modules
    save_cache:
      paths:
        - << pipeline.parameters.package_name >>/node_modules
      key: *cache_key
  restore_node_modules: &restore_node_modules
    restore_cache:
      keys:
        - *cache_key
        - v1-dependencies-

jobs:
  # 差分検知用シェル実行
  trigger-workflows:
    executor: node
    steps:
      - checkout
      - run:
          name: Trigger workflows
          command: chmod +x .circleci/circle_trigger.sh && ls -l .circleci && .circleci/circle_trigger.sh

  package-install-and-lint:
    parameters:
      package_name:
        type: string
    executor: node
    steps:
      - checkout:
          path: ~/monorepo
      - *restore_node_modules
      - run:
          name: Package install
          command: npm install
          working_directory: ~/monorepo/<< parameters.package_name >>
      - *save_node_modules
      - run:
          name: Lint
          command: npm run lint
          working_directory: ~/monorepo/<< parameters.package_name >>

  echo:
    parameters:
      package_name:
        type: string
    executor: node
    steps:
      - checkout:
          path: ~/monorepo
      - run:
          name: Echo
          command: echo "This working_directory is '<< parameters.package_name >>''"
          working_directory: ~/monorepo/<< parameters.package_name >>

workflows:
  version: 2
  ci:
    when: << pipeline.parameters.trigger >>
    jobs:
      - trigger-workflows

  # 変更検知されたプロジェクトのjobが走る
  demo:
    when: << pipeline.parameters.demo >>
    jobs:
      - package-install-and-lint:
          name: demo-install-lint
          package_name: demo

      - echo:
          name: demo-echo
          package_name: demo

  sample:
    when: << pipeline.parameters.sample >>
    jobs:
      - package-install-and-lint:
          name: sample-install-lint
          package_name: sample

      - echo:
          name: sample-echo
          package_name: sample
