version: 2.1

parameters:
  # This parameter is used to trigger the main workflow
  trigger:
    type: boolean
    default: true

  # A parameter per package
  demo:
    type: boolean
    default: false
  sample:
    type: boolean
    default: false

executors:
  node:
    docker:
      - image: circleci/node:10.15.3

jobs:
  trigger-workflows:
    executor: node
    steps:
      - checkout
      - run:
          name: Trigger workflows
          command: chmod +x .circleci/circle_trigger.sh && .circleci/circle_trigger.sh

  build:
    parameters:
      package_name:
        type: string

    executor: node
    working_directory: ~/monorepo/packages/<< parameters.package_name >>

    steps:
      - checkout:
          path: ~/monorepo
      - run:
          name: Content 
          command: |
            cat README.md 
            echo "<< parameters.package_name >> built." > build.txt
      - run:
          name: Build
          command: echo "ビルド << parameters.package_name >> ..."
      - persist_to_workspace:
          root: ~/monorepo
          paths:
            - packages/<< parameters.package_name >>
  echo:
    executor: node
    steps:
      - checkout:
        path: ~/monorepo
      - run:
        command: echo "Hello World tg."


workflows:
  version: 2
  ci:
    when: << pipeline.parameters.trigger >>
    jobs:
      - trigger-workflows

  # Workflows defined for each package.
  demo:
    when: << pipeline.parameters.demo >>
    jobs:
      - echo
  sample:
    when: << pipeline.parameters.sample >>
    jobs:
      - echo