version: 2.1

parameters:
  trigger:
    type: boolean
    default: true

  demo:
    type: boolean
    default: false
  sample:
    type: boolean
    default: false

executors:
  node:
    docker:
      - image: circleci/node:10.15.3

jobs:
  trigger-workflows:
    executor: node
    steps:
      - checkout
      - run:
          name: Trigger workflows
          command: chmod +x .circleci/circle_trigger.sh && ls -l && .circleci/circle_trigger.sh

  package-install-and-lint:
    parameters:
      package_name:
        type: string
    executor: node
    steps:
      - checkout:
          path: ~/monorepo
      - run:
          name: Package install
          command: npm install
          working_directory: ~/monorepo/<< parameters.package_name >>
      - run:
          name: Lint
          command: npm run lint
          working_directory: ~/monorepo/<< parameters.package_name >>

  echo:
    parameters:
      package_name:
        type: string
    executor: node
    steps:
      - checkout:
          path: ~/monorepo
      - run:
          name: Echo 
          command: echo "This working_directory is '<< parameters.package_name >>''"
          working_directory: ~/monorepo/<< parameters.package_name >>

workflows:
  version: 2
  ci:
    when: << pipeline.parameters.trigger >>
    jobs:
      - trigger-workflows

  demo:
    when: << pipeline.parameters.demo >>
    jobs:
      - package-install-and-lint:
          name: demo-install-lint
          package_name: demo
          # filters:
          #   branches:
          #     only:
          #       - develop
      - echo:
          name: demo-echo
          package_name: demo
          # filters:
          #   branches:
          #     only:
          #       - develop

  sample:
    when: << pipeline.parameters.sample >>
    jobs:
      - package-install-and-lint:
          name: sample-install-lint
          package_name: sample
          # filters:
          #   branches:
          #     only:
          #       - develop
      - echo:
          name: sample-echo
          package_name: sample
          # filters:
          #   branches:
          #     only:
          #       - develop
